Local Warehouse model was updated
ShahanAliyev/Cargo pull request #11
Opened 2023-04-21 08:42 UTC by ShahanAliyev

2023-04-21 10:57 UTC, mmzeynalli requested changes

2023-04-21 10:57 UTC, mmzeynalli commented on codes.txt
Never upload temp files to git

2023-04-21 10:57 UTC, mmzeynalli commented on to-do.txt
Check TODO commenting style and extensions in VSCode to nicely visualize them

2023-04-21 16:21 UTC, ShahanAliyev commented on to-do.txt
I thought that mentioned them in gitignore

2023-04-21 16:21 UTC, ShahanAliyev commented on to-do.txt
I thought that I had mentioned them in gitignore

2023-04-22 09:05 UTC, mmzeynalli approved these changes

2023-04-22 09:06 UTC, merged